// Per-environment settings for the crewreg deployment, read from the `crewreg`
// block in cdk.json (or overridden with `-c`). Everything here is validated
// before a single construct is created, because a typo in a hostname or an
// origin would otherwise surface as a certificate that never issues or a browser
// that silently refuses every API call.
//
// Nothing in this file is secret. Secrets are generated by the data stack or set
// by the operator directly in Secrets Manager; they never pass through context.

import { App } from 'aws-cdk-lib';

/**
 * Environments the backend treats as deployed: it fetches its secret-bearing
 * config sections from Secrets Manager as `<environment>/<section>` for each of
 * these, and rejects any other name (backend/config, ADR 0015). `local` is
 * deliberately absent: it reads secrets from a file and is never deployed.
 */
export const DEPLOYED_ENVIRONMENTS = ['dev', 'staging', 'prod'] as const;
export type EnvironmentName = (typeof DEPLOYED_ENVIRONMENTS)[number];

/** Providers the backend's config loader accepts for `llm.provider`. */
export const LLM_PROVIDERS = ['anthropic', 'gemini', 'openai'] as const;
export type LlmProvider = (typeof LLM_PROVIDERS)[number];

/**
 * The non-secret half of the backend's `llm` section. It is written into the
 * `<env>/llm` secret as a template; the operator adds `api_key` once.
 */
export interface LlmSettings {
  readonly provider: LlmProvider;
  readonly textModel: string;
  readonly visionModel: string;
  readonly maxTokens: number;
}

/** The backend's `extract` section. Never secret, so it lives in the config file. */
export interface ExtractSettings {
  readonly minTextChars: number;
  readonly visionDpi: number;
  readonly maxVisionPages: number;
}

export interface EnvironmentConfig {
  readonly envName: EnvironmentName;
  /** AWS region for every resource and for the backend's Secrets Manager client. */
  readonly region: string;
  /** Public hostname of the API. Caddy requests a certificate for exactly this name. */
  readonly apiHost: string;
  /** Let's Encrypt account email (expiry notices). */
  readonly acmeEmail: string;
  /** Recipient of the monthly budget alerts. */
  readonly budgetEmail: string;
  /** Monthly cost ceiling for the account-wide budget alert, in USD. */
  readonly budgetUsd: number;
  /** Browser origins allowed by the backend's CORS middleware. Empty disables CORS. */
  readonly corsAllowedOrigins: readonly string[];
  /** `owner/repo` of the backend, whose GitHub Actions may assume the deploy role. */
  readonly githubRepo: string;
  /** EC2 instance type, e.g. `t3.micro`. A Graviton type switches the AMI to arm64. */
  readonly instanceType: string;
  /** Optional AMI pin. When absent the latest Amazon Linux 2023 is looked up once and cached in cdk.context.json. */
  readonly amiId?: string;
  /**
   * Optional Route 53 public hosted zone to create and manage, e.g. `example.com`.
   * When set, `apiHost` must be inside it and the app stack writes its A record;
   * when absent, the A record is the operator's job at the registrar.
   */
  readonly hostedZoneName?: string;
  readonly llm: LlmSettings;
  readonly extract: ExtractSettings;
}

/** Prefix under which every context error is reported, e.g. `crewreg.dev.apiHost`. */
const CONTEXT_KEY = 'crewreg';

const HOSTNAME_RE = /^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/;
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const INSTANCE_TYPE_RE = /^[a-z][a-z0-9-]*\.[a-z0-9]+$/;
const GITHUB_REPO_RE = /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/;
const AMI_ID_RE = /^ami-[0-9a-f]{8,17}$/;

/**
 * Reads and validates the configuration for `envName` from the app's context.
 * Throws with the offending context path when anything is missing or malformed.
 */
export function loadEnvironmentConfig(app: App, envName: string): EnvironmentConfig {
  const all: unknown = app.node.tryGetContext(CONTEXT_KEY);
  if (!isRecord(all)) {
    throw new Error(`context "${CONTEXT_KEY}" is missing from cdk.json`);
  }
  const raw = all[envName];
  if (raw === undefined) {
    throw new Error(`context "${CONTEXT_KEY}.${envName}" is missing from cdk.json (known: ${Object.keys(all).join(', ')})`);
  }
  // `-c amiId=ami-...` at the command line pins the image without editing cdk.json.
  const amiOverride: unknown = app.node.tryGetContext('amiId');
  const merged = amiOverride === undefined || !isRecord(raw) ? raw : { ...raw, amiId: amiOverride };
  return validateEnvironmentConfig(envName, merged);
}

/**
 * Validates one environment's raw context block. Pure, so tests can feed it
 * objects directly; every failure names the path the operator has to fix.
 */
export function validateEnvironmentConfig(envName: string, raw: unknown): EnvironmentConfig {
  const at = (field: string) => `${CONTEXT_KEY}.${envName}.${field}`;

  if (!isEnvironmentName(envName)) {
    throw new Error(`${CONTEXT_KEY}.${envName}: environment must be one of ${DEPLOYED_ENVIRONMENTS.join('|')}`);
  }
  if (!isRecord(raw)) {
    throw new Error(`${CONTEXT_KEY}.${envName} must be an object`);
  }

  const region = requireString(raw, 'region', at);
  if (!/^[a-z]{2}-[a-z]+-\d$/.test(region)) {
    throw new Error(`${at('region')} "${region}" is not an AWS region name`);
  }

  const apiHost = requireString(raw, 'apiHost', at).toLowerCase();
  if (!HOSTNAME_RE.test(apiHost)) {
    throw new Error(`${at('apiHost')} "${apiHost}" is not a DNS hostname (no scheme, no path)`);
  }

  const acmeEmail = requireString(raw, 'acmeEmail', at);
  if (!EMAIL_RE.test(acmeEmail)) {
    throw new Error(`${at('acmeEmail')} "${acmeEmail}" is not an email address`);
  }

  const budgetEmail = requireString(raw, 'budgetEmail', at);
  if (!EMAIL_RE.test(budgetEmail)) {
    throw new Error(`${at('budgetEmail')} "${budgetEmail}" is not an email address`);
  }

  const budgetUsd = requirePositiveInteger(raw, 'budgetUsd', at);

  const corsAllowedOrigins = requireStringArray(raw, 'corsAllowedOrigins', at);
  corsAllowedOrigins.forEach((origin, i) => {
    if (!isOrigin(origin)) {
      throw new Error(`${at(`corsAllowedOrigins[${i}]`)} "${origin}" must be an absolute http(s)://host[:port] origin with no path`);
    }
  });

  const githubRepo = requireString(raw, 'githubRepo', at);
  if (!GITHUB_REPO_RE.test(githubRepo)) {
    throw new Error(`${at('githubRepo')} "${githubRepo}" must be owner/repo`);
  }

  const instanceType = requireString(raw, 'instanceType', at);
  if (!INSTANCE_TYPE_RE.test(instanceType)) {
    throw new Error(`${at('instanceType')} "${instanceType}" is not an EC2 instance type`);
  }

  let amiId: string | undefined;
  if (raw.amiId !== undefined) {
    if (typeof raw.amiId !== 'string' || !AMI_ID_RE.test(raw.amiId)) {
      throw new Error(`${at('amiId')} must look like ami-0123456789abcdef0`);
    }
    amiId = raw.amiId;
  }

  let hostedZoneName: string | undefined;
  if (raw.hostedZoneName !== undefined) {
    if (typeof raw.hostedZoneName !== 'string' || !HOSTNAME_RE.test(raw.hostedZoneName.toLowerCase())) {
      throw new Error(`${at('hostedZoneName')} must be a DNS name such as example.com`);
    }
    hostedZoneName = raw.hostedZoneName.toLowerCase();
    if (apiHost !== hostedZoneName && !apiHost.endsWith(`.${hostedZoneName}`)) {
      throw new Error(`${at('apiHost')} "${apiHost}" is not inside hostedZoneName "${hostedZoneName}"`);
    }
  }

  const llm = validateLlm(raw.llm, (f) => at(`llm.${f}`));
  const extract = validateExtract(raw.extract, (f) => at(`extract.${f}`));

  return {
    envName,
    region,
    apiHost,
    acmeEmail,
    budgetEmail,
    budgetUsd,
    corsAllowedOrigins,
    githubRepo,
    instanceType,
    amiId,
    hostedZoneName,
    llm,
    extract,
  };
}

/**
 * CPU architecture implied by an instance type: Graviton families (t4g, m7g,
 * c7g, r8g, ...) and a1 are arm64; everything else is x86_64. Drives both the
 * AMI lookup and the Caddy download on the instance.
 */
export function instanceArchitecture(instanceType: string): 'arm64' | 'x86_64' {
  const family = instanceType.split('.')[0];
  if (family === 'a1' || /^[a-z]+\d+[a-z]*g[a-z]*$/.test(family)) {
    return 'arm64';
  }
  return 'x86_64';
}

/** True for `scheme://host[:port]` with an http(s) scheme and nothing after the host. */
export function isOrigin(value: string): boolean {
  if (value.includes('*')) {
    return false;
  }
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    return false;
  }
  const bareHost = url.hostname !== '' && url.username === '' && url.password === '';
  const noTail = (url.pathname === '' || url.pathname === '/') && url.search === '' && url.hash === '';
  const schemeOk = url.protocol === 'http:' || url.protocol === 'https:';
  // `new URL` normalises away a trailing slash, so insist the operator wrote none.
  return bareHost && noTail && schemeOk && !value.endsWith('/');
}

function validateLlm(raw: unknown, at: (f: string) => string): LlmSettings {
  if (!isRecord(raw)) {
    throw new Error(`${at('')} must be an object`);
  }
  const provider = requireString(raw, 'provider', at);
  if (!isLlmProvider(provider)) {
    throw new Error(`${at('provider')} "${provider}" must be one of ${LLM_PROVIDERS.join('|')}`);
  }
  return {
    provider,
    textModel: requireString(raw, 'textModel', at),
    visionModel: requireString(raw, 'visionModel', at),
    maxTokens: requirePositiveInteger(raw, 'maxTokens', at),
  };
}

function validateExtract(raw: unknown, at: (f: string) => string): ExtractSettings {
  if (!isRecord(raw)) {
    throw new Error(`${at('')} must be an object`);
  }
  return {
    minTextChars: requirePositiveInteger(raw, 'minTextChars', at),
    visionDpi: requirePositiveInteger(raw, 'visionDpi', at),
    maxVisionPages: requirePositiveInteger(raw, 'maxVisionPages', at),
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isEnvironmentName(value: string): value is EnvironmentName {
  return (DEPLOYED_ENVIRONMENTS as readonly string[]).includes(value);
}

function isLlmProvider(value: string): value is LlmProvider {
  return (LLM_PROVIDERS as readonly string[]).includes(value);
}

function requireString(raw: Record<string, unknown>, field: string, at: (f: string) => string): string {
  const value = raw[field];
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`${at(field)} is required`);
  }
  return value.trim();
}

function requirePositiveInteger(raw: Record<string, unknown>, field: string, at: (f: string) => string): number {
  const value = raw[field];
  if (typeof value !== 'number' || !Number.isInteger(value) || value <= 0) {
    throw new Error(`${at(field)} must be a positive integer`);
  }
  return value;
}

function requireStringArray(raw: Record<string, unknown>, field: string, at: (f: string) => string): string[] {
  const value = raw[field];
  if (!Array.isArray(value) || value.some((v) => typeof v !== 'string')) {
    throw new Error(`${at(field)} must be an array of strings (use [] for none)`);
  }
  return value.map((v: string) => v.trim());
}
