// Renders the EC2 user-data (cloud-init) script for the API instance from the
// templates in instance/. The rendered script first writes every file the
// instance needs, then runs instance/bootstrap.sh. Keeping the files as real
// files in the repo (rather than strings in TypeScript) means they can be read,
// linted and diffed on their own.
//
// Placeholders are `{{NAME}}` and are substituted here. Values come from the
// validated EnvironmentConfig plus the resources the app stack created, so a
// placeholder left unfilled is a bug and fails synthesis.

import * as fs from 'fs';
import * as path from 'path';

import { EnvironmentConfig } from './config';

/** Directory holding the instance templates, resolved relative to this file. */
const INSTANCE_DIR = path.join(__dirname, '..', 'instance');

/**
 * EC2 refuses user-data above 16 KiB (before base64). The rendered script is
 * checked against this so the failure is at synth time with a clear message,
 * not at launch with an opaque one.
 */
export const USER_DATA_LIMIT_BYTES = 16 * 1024;

export interface UserDataParams {
  readonly config: EnvironmentConfig;
  /** Name of the artifacts bucket the instance pulls releases from. */
  readonly artifactsBucket: string;
  /** CloudWatch log group names. Created by the app stack so retention is managed. */
  readonly serverLogGroup: string;
  readonly caddyLogGroup: string;
  /** Caddy release to install, e.g. `2.11.4` (no leading v). */
  readonly caddyVersion: string;
}

/** A file the rendered script writes before bootstrap runs. */
interface InstalledFile {
  readonly path: string;
  readonly content: string;
  /** Octal mode string, e.g. `0644`. Ownership is fixed up by bootstrap.sh. */
  readonly mode: string;
}

/**
 * Renders the complete user-data script. Throws if a placeholder is left
 * unfilled or the result exceeds the EC2 size limit.
 */
export function renderUserData(params: UserDataParams): string {
  const values = placeholderValues(params);
  const files: InstalledFile[] = [
    { path: '/etc/crewreg/config.yaml', content: renderConfigYaml(params.config), mode: '0640' },
    { path: '/etc/crewreg/deploy.env', content: renderDeployEnv(params), mode: '0640' },
    { path: '/etc/crewreg/cloudwatch-agent.json', content: template('cloudwatch-agent.json', values), mode: '0644' },
    { path: '/etc/systemd/system/crewreg.service', content: template('crewreg.service', values), mode: '0644' },
    { path: '/etc/systemd/system/caddy.service', content: template('caddy.service', values), mode: '0644' },
    { path: '/etc/caddy/Caddyfile', content: template('Caddyfile', values), mode: '0644' },
    { path: '/etc/logrotate.d/crewreg', content: template('logrotate-crewreg', values), mode: '0644' },
    { path: '/usr/local/bin/crewreg-deploy', content: template('crewreg-deploy.sh', values), mode: '0755' },
  ];

  const script = [
    '#!/bin/bash',
    '# Generated by shipping-infra (lib/user-data.ts). Do not edit on the instance.',
    'set -euo pipefail',
    'exec > >(tee -a /var/log/crewreg-bootstrap.log) 2>&1',
    '',
    ...files.map(writeFileBlock),
    template('bootstrap.sh', values),
  ].join('\n');

  const size = Buffer.byteLength(script, 'utf8');
  if (size > USER_DATA_LIMIT_BYTES) {
    throw new Error(`rendered user-data is ${size} bytes, above the EC2 limit of ${USER_DATA_LIMIT_BYTES}`);
  }
  return script;
}

/**
 * The backend's config file for a deployed environment. The `llm`, `database`
 * and `auth` sections are omitted on purpose: the loader replaces them from
 * Secrets Manager (`<env>/<section>`) and would ignore anything written here.
 */
export function renderConfigYaml(config: EnvironmentConfig): string {
  const origins = config.corsAllowedOrigins.length === 0
    ? '  allowed_origins: []'
    : ['  allowed_origins:', ...config.corsAllowedOrigins.map((o) => `    - ${o}`)].join('\n');

  return [
    '# Written by shipping-infra at first boot. Secrets are NOT here: the llm,',
    '# database and auth sections come from AWS Secrets Manager (ADR 0015).',
    `environment: ${config.envName}`,
    `region: ${config.region}`,
    'extract:',
    `  min_text_chars: ${config.extract.minTextChars}`,
    `  vision_dpi: ${config.extract.visionDpi}`,
    `  max_vision_pages: ${config.extract.maxVisionPages}`,
    'cors:',
    origins,
    '',
  ].join('\n');
}

function renderDeployEnv(params: UserDataParams): string {
  return [
    '# Sourced by /usr/local/bin/crewreg-deploy. Written by shipping-infra.',
    `ARTIFACTS_BUCKET=${params.artifactsBucket}`,
    `AWS_DEFAULT_REGION=${params.config.region}`,
    '',
  ].join('\n');
}

function placeholderValues(params: UserDataParams): Record<string, string> {
  return {
    ENV: params.config.envName,
    REGION: params.config.region,
    API_HOST: params.config.apiHost,
    ACME_EMAIL: params.config.acmeEmail,
    GITHUB_REPO: params.config.githubRepo,
    ARTIFACTS_BUCKET: params.artifactsBucket,
    SERVER_LOG_GROUP: params.serverLogGroup,
    CADDY_LOG_GROUP: params.caddyLogGroup,
    CADDY_VERSION: params.caddyVersion,
  };
}

/** Reads instance/<name> and substitutes every `{{KEY}}`; unknown keys fail loudly. */
function template(name: string, values: Record<string, string>): string {
  const raw = fs.readFileSync(path.join(INSTANCE_DIR, name), 'utf8').replace(/\r\n/g, '\n');
  const rendered = raw.replace(/\{\{([A-Z0-9_]+)\}\}/g, (_match, key: string) => {
    const value = values[key];
    if (value === undefined) {
      throw new Error(`instance/${name}: no value for placeholder {{${key}}}`);
    }
    return value;
  });
  const leftover = rendered.match(/\{\{[^}]*\}\}/);
  if (leftover !== null && !name.endsWith('.json')) {
    throw new Error(`instance/${name}: unrenderable placeholder ${leftover[0]}`);
  }
  return rendered;
}

/**
 * A quoted heredoc that writes one file. The delimiter is quoted so nothing in
 * the content is expanded by the shell, which matters for the deploy script and
 * the Caddyfile (both contain `$`).
 */
function writeFileBlock(file: InstalledFile): string {
  const delimiter = '__CREWREG_FILE__';
  if (file.content.includes(delimiter)) {
    throw new Error(`${file.path}: content contains the heredoc delimiter`);
  }
  const body = file.content.endsWith('\n') ? file.content : `${file.content}\n`;
  return [
    `mkdir -p "$(dirname '${file.path}')"`,
    `cat > '${file.path}' <<'${delimiter}'`,
    body.replace(/\n$/, ''),
    delimiter,
    `chmod ${file.mode} '${file.path}'`,
    '',
  ].join('\n');
}
